# The URL the site will be built for
base_url = "https://benliepert.github.io/blog/"

# The site title, shown in the browser tab
title = "Ben Liepert's Blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "d3c3nt"
# theme = "oceanic-zen"

[markdown.highlighting]
# Syntax highlighting is on when this section is present.
# Theme options: https://github.com/getzola/giallo?tab=readme-ov-file#built-in
theme = "one-dark-pro"

[extra]
# Put all your custom variables here

  d3_nav = [
    { name = "ABOUT", path = "/blog/" },
    { name = "POSTS", path = "/blog/posts/" },
  ]
  d3_author = "benliepert"

  # To customize the favicon:
  # d3_icon = "path/to/icon"
