# The URL the site will be built for
base_url = "https://benliepert.github.io/blog/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "d3c3nt"
# theme = "oceanic-zen"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# Theme options: https://www.getzola.org/documentation/getting-started/configuration/#highlight_theme
highlight_theme = "one-dark"

[extra]
# Put all your custom variables here

  d3_nav = [
    { name = "ABOUT", path = "/blog/" },
    { name = "POSTS", path = "/blog/posts/" },
  ]
  d3_author = "benliepert"

  # To customize the favicon:
  # d3_icon = "path/to/icon"
